[package]
name = "rust-rtl-sdr-waterfall-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.34", features = ["derive"] }
rtlsdr_mt = "2.2.0"
rustfft = "6.2.0"
sdl2 = { version = "0.37.0", features = ["ttf"] }
